image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      conda init bash

  - command: conda env create --file environment.yml
    name: Create Conda environment

  - command: conda activate leticia
    name: Activate Conda environment
