image: gitpod/workspace-base

tasks:
- name: install mamba and lotus2 dependencies
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n lotus2 -c conda-forge -c bioconda \
      lotus2

    mamba clean --all -y

    mamba install -n lotus2 -c conda-forge -c bioconda \
      lotus2

    mamba clean --all -y

    mamba activate lotus2

    cd /workspace
    git clone https://github.com/hildebra/lotus2
    cd lotus2
    
    chmod +x ./lotus2

    # set paths in Earl Grey Script

    echo "Setting path variables in script"
    SCRIPT_DIR=$(realpath ./scripts/)
    sed -i "s|SCRIPT_DIR=.*|SCRIPT_DIR=${SCRIPT_DIR}|g" ./lotus2
    sed -i "s|SCRIPT_DIR=.*|SCRIPT_DIR=${SCRIPT_DIR}|g" ./configs/sdm_src*

    echo "Path variables set"

    echo "Installing sa-ssr"
    cd ${SCRIPT_DIR} && chmod a+w ${SCRIPT_DIR}
    git clone https://github.com/ridgelab/SA-SSR && cd ./SA-SSR/
    sed -i "s|PREFIX=/usr/local/bin|PREFIX=${SCRIPT_DIR}|g" Makefile && make && make install
    cd ${SCRIPT_DIR}

    # Extract tRNAdb
    echo "Extracting zip archives"
    tar -zxf ${SCRIPT_DIR}/bin/LTR_FINDER.x86_64-1.0.7/tRNAdb.tar.gz --directory ${SCRIPT_DIR}/bin/LTR_FINDER.x86_64-1.0.7/
    echo "Extracted required archives"

    # Message Complete
    echo "Remember to activate the lotus2 conda environment before running earlGrey"
    export PATH=$PATH:$(realpath .)
    echo "earlGrey is ready to use. To execute from any directory, add earlGrey to path by pasting the code (minus the square brackets) below..."
    echo '[export PATH=$PATH:$(realpath .)]'
    cd /workspace/EarlGrey
    export PATH=$PATH:$(realpath .)
    export PERL5LIB=/workspace/conda/envs/earlGrey/share/RepeatMasker/:$PERL5LIB

  command: |
    /workspace/conda/bin/mamba init bash
    source ~/.bashrc
    mamba activate lotus2
    cd /workspace/lotus2
    export PATH=$PATH:$(realpath .)
    export PERL5LIB=/workspace/conda/envs/lotus2
    cd /workspace

# - name: install Dfam.h5.gz from alternate source
#   init: |
#     sleep 100
#     pkill wget
#     curl http://dfam.cog.sanger.ac.uk/Dfam.h5.gz | zcat > /workspace/conda/env/earlGrey/share/RepeatMasker/Libraries/Dfam.h5

github:
  prebuilds:
    master: true
    branches: true
